[[redirects]]
  from = "/api/*"
  to = "http://34.93.62.26:8000/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/hls/*"
  to = "https://stream.avakai.aerovhyn.in/hls/:splat"
  status = 200
  force = true
