[[redirects]]
from = "/api/*"
to = "http://34.93.155.20:8000/:splat"
status = 200
force = true

[[redirects]]
from = "/hls/*"
to = "https://stream.avakai.aerovhyn.in/hls/:splat"
status = 200
force = true
